version: '3.9'

volumes:
  database_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

services:
  cds_database:
    image: mysql
    container_name: cds_database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - database_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/minio

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data/redis:/var/lib/redis

  cds_app:
    build:
      context: .
    container_name: cds_app
    depends_on:
      - cds_database
      - redis
      - minio
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080'