spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  liquibase:
    change-log: classpath:database/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${MYSQL_DATABASE}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        current_session_context_class: thread
        hbm2ddl:
          auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  servlet:
    session:
      timeout: 1h

minio:
  bucket: ${MINIO_BUCKET}
  endpoint: http://localhost:9000
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}